# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build farm-budget`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t farm-budget`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system farm-budget && \
          adduser --system -G farm-budget farm-budget

COPY dist/farm-budget farm-budget/
RUN chown -R farm-budget:farm-budget .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix farm-budget --omit=dev -f install

CMD [ "node", "farm-budget" ]
